-- Hardware Detection Module for dcli
-- This module automatically detects your hardware and selects appropriate packages
-- Generated by: dcli generate hardware
---@diagnostic disable: undefined-global -- dcli globals are provided by dcli runtime

local hardware = {}

-- Best-effort chassis/vendor detection so we can add vendor-specific tools
local function detect_chassis_vendor()
    local candidates = {
        "/sys/class/dmi/id/chassis_vendor",
        "/sys/class/dmi/id/board_vendor",
        "/sys/class/dmi/id/sys_vendor",
    }

    for _, path in ipairs(candidates) do
        if dcli.file.exists(path) then
            local value = dcli.file.read(path)
            if value and value ~= "" then
                return value:gsub("%s+$", "")
            end
        end
    end

    return "unknown"
end

-- Get CPU vendor
function hardware.get_cpu_packages()
    local packages = {}
    local cpu = dcli.hardware.cpu_vendor()

    if cpu == "intel" then
        table.insert(packages, "intel-ucode")
    elseif cpu == "amd" then
        table.insert(packages, "amd-ucode")
    end

    return packages
end

-- Get GPU packages based on detected hardware
function hardware.get_gpu_packages()
    local packages = {}
    local is_laptop = dcli.hardware.is_laptop()
    local chassis = dcli.hardware.chassis_type()
    local is_desktop = chassis == "desktop"

    -- Always include base mesa for OpenGL
    table.insert(packages, "mesa")
    table.insert(packages, "vulkan-icd-loader")
    table.insert(packages, "lib32-vulkan-icd-loader")

    if dcli.hardware.has_nvidia() then
        if is_desktop then
            -- Desktop (stock Arch kernels): use DKMS so it works with linux/linux-lts/linux-zen and custom kernels
            table.insert(packages, "nvidia-open-dkms") -- or "nvidia-dkms" if you prefer the proprietary module
            table.insert(packages, "dkms")
            table.insert(packages, "linux-headers")
        elseif is_laptop then
            -- Laptop/Deck: Use DKMS + PRIME switching
            table.insert(packages, "nvidia-open-dkms") -- or "nvidia-dkms"
            table.insert(packages, "dkms")
            table.insert(packages, "nvidia-prime")     -- For GPU switching
        end
        table.insert(packages, "nvidia-utils")
        table.insert(packages, "nvidia-settings")
        table.insert(packages, "lib32-nvidia-utils") -- 32-bit support for games
        table.insert(packages, "opencl-nvidia")
        table.insert(packages, "lib32-opencl-nvidia")
        table.insert(packages, "libva-nvidia-driver")
    end

    if dcli.hardware.has_amd_gpu() then
        table.insert(packages, "vulkan-radeon")
        table.insert(packages, "lib32-vulkan-radeon")
        table.insert(packages, "libva-mesa-driver") -- Hardware video acceleration
        table.insert(packages, "lib32-mesa")
    end

    if dcli.hardware.has_intel_gpu() then
        table.insert(packages, "vulkan-intel")
        table.insert(packages, "lib32-vulkan-intel")
        table.insert(packages, "intel-media-driver") -- Hardware video acceleration
        table.insert(packages, "lib32-mesa")
    end

    return packages
end

-- Get laptop-specific packages
function hardware.get_laptop_packages()
    local packages = {}

    if dcli.hardware.is_laptop() or dcli.hardware.has_battery() then
        table.insert(packages, "tlp")      -- Power management
        table.insert(packages, "tlp-rdw")  -- Radio device wizard
        table.insert(packages, "powertop") -- Power consumption analyzer
        -- Uncomment if you want brightness control
        -- table.insert(packages, "brightnessctl")
    end

    return packages
end

-- Get services to enable/disable based on hardware
function hardware.get_services()
    local services = {
        enabled = {},
        disabled = {}
    }

    if dcli.hardware.is_laptop() or dcli.hardware.has_battery() then
        table.insert(services.enabled, "tlp")
    end

    return services
end

-- Get vendor-specific packages (e.g., ASUS laptops)
function hardware.get_vendor_packages()
    local packages = {}
    local vendor = detect_chassis_vendor():lower()

    if vendor:find("asus") then
        table.insert(packages, "asusctl")
        table.insert(packages, "supergfxctl")
        table.insert(packages, "rog-control-center")
    end

    return packages
end

-- Combine all packages
function hardware.get_all_packages()
    local packages = {}

    -- Add CPU packages
    for _, pkg in ipairs(hardware.get_cpu_packages()) do
        table.insert(packages, pkg)
    end

    -- Add GPU packages
    for _, pkg in ipairs(hardware.get_gpu_packages()) do
        table.insert(packages, pkg)
    end

    -- Add laptop packages
    for _, pkg in ipairs(hardware.get_laptop_packages()) do
        table.insert(packages, pkg)
    end

    -- Add vendor-specific packages
    for _, pkg in ipairs(hardware.get_vendor_packages()) do
        table.insert(packages, pkg)
    end

    -- Always include firmware
    table.insert(packages, "linux-firmware")

    return packages
end

-- Build metadata for display
function hardware.get_metadata()
    return {
        cpu = dcli.hardware.cpu_vendor(),
        gpus = dcli.hardware.gpu_vendors(),
        is_laptop = dcli.hardware.is_laptop(),
        has_battery = dcli.hardware.has_battery(),
        chassis = dcli.hardware.chassis_type(),
        chassis_vendor = detect_chassis_vendor(),
        hostname = dcli.system.hostname(),
    }
end

-- Export module configuration
return {
    description = "Auto-detected hardware configuration for " .. dcli.system.hostname(),
    packages = hardware.get_all_packages(),
    services = hardware.get_services(),
    metadata = hardware.get_metadata(),

    -- Optional: Add hooks for hardware-specific setup
    -- pre_install_hook = "scripts/hardware-pre.sh",
    -- post_install_hook = "scripts/hardware-post.sh",
}
