-- Storage Detection Module for dcli
-- This module automatically detects storage devices and filesystems
-- Generated by: dcli generate storage

local storage = {}

-- Get packages for SSD optimization
function storage.get_ssd_packages()
    local packages = {}

    if dcli.storage.has_ssd() then
        table.insert(packages, "util-linux")  -- For fstrim
    end

    return packages
end

-- Get packages for NVMe drives
function storage.get_nvme_packages()
    local packages = {}

    if dcli.storage.has_nvme() then
        table.insert(packages, "nvme-cli")  -- NVMe management tools
    end

    return packages
end

-- Get filesystem-specific packages
function storage.get_filesystem_packages()
    local packages = {}

    -- Check root filesystem
    local root_fs = dcli.storage.filesystem("/")

    if root_fs == "btrfs" then
        table.insert(packages, "btrfs-progs")
        table.insert(packages, "snapper")  -- Snapshot management
        table.insert(packages, "snap-pac") -- Pacman hooks for snapshots
    elseif root_fs == "ext4" then
        table.insert(packages, "e2fsprogs")
    elseif root_fs == "xfs" then
        table.insert(packages, "xfsprogs")
    elseif root_fs == "f2fs" then
        table.insert(packages, "f2fs-tools")
    end

    -- Check if home is on different filesystem
    local home_fs = dcli.storage.filesystem("/home")
    if home_fs and home_fs ~= root_fs then
        if home_fs == "btrfs" then
            table.insert(packages, "btrfs-progs")
        elseif home_fs == "ext4" then
            table.insert(packages, "e2fsprogs")
        elseif home_fs == "xfs" then
            table.insert(packages, "xfsprogs")
        end
    end

    return packages
end

-- Get services based on storage configuration
function storage.get_services()
    local services = {
        enabled = {},
        disabled = {}
    }

    -- Enable fstrim timer for SSDs
    if dcli.storage.has_ssd() then
        table.insert(services.enabled, "fstrim.timer")
    end

    return services
end

-- Combine all packages
function storage.get_all_packages()
    local packages = {}

    -- Add SSD packages
    for _, pkg in ipairs(storage.get_ssd_packages()) do
        table.insert(packages, pkg)
    end

    -- Add NVMe packages
    for _, pkg in ipairs(storage.get_nvme_packages()) do
        table.insert(packages, pkg)
    end

    -- Add filesystem packages
    for _, pkg in ipairs(storage.get_filesystem_packages()) do
        table.insert(packages, pkg)
    end

    return packages
end

-- Get storage metadata
function storage.get_metadata()
    local disks = dcli.storage.list_disks()
    local disk_info = {}

    for _, disk in ipairs(disks) do
        local dtype = dcli.storage.disk_type(disk)
        local size = dcli.storage.disk_size(disk)

        table.insert(disk_info, {
            name = disk,
            type = dtype,
            size_gb = size and string.format("%.2f", size / (1024*1024*1024)) or "unknown"
        })
    end

    return {
        hostname = dcli.system.hostname(),
        root_filesystem = dcli.storage.filesystem("/"),
        has_ssd = dcli.storage.has_ssd(),
        has_hdd = dcli.storage.has_hdd(),
        has_nvme = dcli.storage.has_nvme(),
        has_swap = dcli.storage.has_swap(),
        disks = disk_info,
    }
end

-- Export module configuration
return {
    description = "Auto-detected storage configuration for " .. dcli.system.hostname(),
    packages = storage.get_all_packages(),
    services = storage.get_services(),
    metadata = storage.get_metadata(),
}
