local packages = {
    "android-studio",
    "code",
    "zed",
    "chromium",
    "clang",
    "cmake",
    "ninja",
    "gtk3",
    "libstdc++5",
    "curl",
    "git",
    "unzip",
    "xz",
    "zip",
    "glu",
    "helix",
    "claude-code",
    "yazi",
    "opencode",
    "tmux",
    "ollama",
    "fish",
    "gnome-boxes",
}

return {
    description = "Development tools including IDEs and browsers",
    packages = packages,
    conflicts = {},
}
